//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILLINFO
    {
        public int BILLID { get; set; }
        public int GOODSID { get; set; }
        public Nullable<int> COUNT { get; set; }
    
        public virtual BILL BILL { get; set; }
        public virtual GOODS GOOD { get; set; }
    }
}
